# Math

In [3]:
print("Hello World")

Hello World


In [15]:
print( 1 + 2 )

3


In [16]:
print( 1 - 5 )

-4


In [17]:
print( 4 * 5 ) # multiplication
print( 4 / 5 ) # division
print( 3 ** 2 ) # exponent
print( 25 ** 0.5 ) # square root

20
0.8
9
5.0


## Order of operations

In [18]:
print( 1 + 2 * 3 )
print( 1 + ( 2 * 3 ) )
print( ( 1 + 2 ) * 3 )

7
7
9


## Varibales
A variable is a symbol that contains data

In [21]:
x = 1
y = 10
z = 10001
print ( x )
print ( y )
print ( z )

1
10
10001


In [22]:
print( x, y, z )

1 10 10001


In [24]:
print( x + y)
a = x + y
print( a )

11
11


## Dynamic typing (type of variable)

In [28]:
x = 2
print(x, type(x))

x = 2.7
print(x, type(x))

x = "Hello"
print(x, type(x))

2 <class 'int'>
2.7 <class 'float'>
Hello <class 'str'>


## Variable names

- Contain only lower-case letters (abcde... NOT ABCDE...)
- Multi-name variables shoulde be separatede with underscores `_`
- Must start with a letter

In [33]:
x0 = 1
x1 = 10
x2 = 200
print(x0,x1,x2)

1 10 200


In [36]:
0x = 100

SyntaxError: invalid hexadecimal literal (1198918811.py, line 1)

In [38]:
x9911231564684132189516651 = 100
print(x9911231564684132189516651)

100


In [37]:
a = 1
x = 10
abc = 100

print(abc)

ABC = 1000 # not an error, but not Python convention
print(ABC)

my_favorite_ice_cream = 10 # alligned with Python convention
print(my_favorite_ice_cream)

myFavoriteIceCream = 200 # not an error, but not Python convention
print(myFavoriteIceCream)

100
1000
10
200


## Lists and tuples
A list contains multiple variables in a sequence
A tuple is a list that cannot be changed

In [42]:
x = [0,5,8]
y = (0,5,8)

print(x)
print(type(x))
print(y)
print(type(y))

[0, 5, 8]
<class 'list'>
(0, 5, 8)
<class 'tuple'>


In [44]:
x = [0,5,8]

print(x[0]) # first element of x; "zero indexing"
print(x[1]) # second element of x
print(x[2]) # third element of x

0
5
8


In [45]:
print(x[3])

IndexError: list index out of range

In [47]:
print(x[-1]) # Last element
print(x[-2]) # Second last element
print(x[-3]) # Third last element

8
5
0


In [48]:
print(x[-4]) # Fourth last element

IndexError: list index out of range

In [49]:
x = [0,10,100]
x[0] = 2000
x[1] = -5

print(x)

[2000, -5, 100]


In [50]:
x = (0,10,100)
print(x[0])

0


In [51]:
print(x(0))

TypeError: 'tuple' object is not callable

In [52]:
x = (0,10,100)
x[0] = 200

TypeError: 'tuple' object does not support item assignment

In [53]:
g = (0,0,-9812) # gravity vector does not change, so use a tuple

# Arrays

Creating arrays is usually done in Python using the NumPy package

NumPy : Numerical Python

- A package is like a librarym containing several programming tools like functions and variables.
- Packages must be accessed using the "import" command in Python.

In [57]:
import numpy

x = numpy.array([0,5,8])

print(x, type(x)) # n-dimensional array

[0 5 8] <class 'numpy.ndarray'>


In [58]:
print(x[0])
print(x[1])

0
5


In [61]:
print(x+1)
print(x*2)
print(x/4)
print(x**2)
print(x**0.5)

[1 6 9]
[ 0 10 16]
[0.   1.25 2.  ]
[ 0 25 64]
[0.         2.23606798 2.82842712]


In [60]:
a = [0,5,8]
print(a+1)

TypeError: can only concatenate list (not "int") to list

In [62]:
import numpy as np
a = np.array([0,1,5])
b = np.array([10,10,0])

print(a+b)

[10 11  5]


In [63]:
c = [0,1,5]
d = [10,10,0]

print(c+d)

[0, 1, 5, 10, 10, 0]


# Functions
A function accepts inputs variables (called "input arguments"), performs calculations, and then returns output variables (called "output arguments") to the caller.

In [67]:
def my_function(x):
    y = x + 1
    return y

print(my_function(10))

a = my_function(10)

print(a)

11
11


- `def`: define function
- `my_function` is the function name (should be named like variable names by convention)
- `x`: input argument
- `y`: output argument
- `return` indicates that the function is finished

In [71]:
def my_function(x,y):
    z = x + y
    q = 100
    return z, q

a,b = my_function(1,2)
print(a,b)

3 100


In [74]:
a = [1,2] # Lists do appear with comma when being printed
print(a)

a = np.array([1,2]) # Arrays do
print(a)

[1, 2]
[1 2]
